Setup-hello-microverse-project
OTMANE-ECHCHAFYKY/hello-microverse pull request #2
Opened 2023-03-21 15:19 UTC by OTMANE-ECHCHAFYKY

Adding some new files to make the code readable, also to style the page and a descriptive README.md file

2023-03-22 10:14 UTC, didierganthier requested changes
Hi @OTMANE-ECHCHAFYKY ,

🎉 Great job on addressing the feedback from the [previous review](https://github.com/OTMANE-ECHCHAFYKY/hello-microverse/pull/1)! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/e56n4Z0mmkxZS/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-03-22 10:14 UTC, didierganthier commented on README.md
> +<!-- TABLE OF CONTENTS -->
Well done on the README 👍🏽 but as requested by the previous reviewer [here](https://github.com/OTMANE-ECHCHAFYKY/hello-microverse/pull/1) all the comments should be removed ❌  and these are considered comments as well. 🤔

2023-03-22 10:14 UTC, didierganthier commented on README.md
> +- [❓ FAQ (OPTIONAL)](#faq)
[OPTIONAL] This is optional (just like the FAQ) 😆 but since you don't have a `FAQ` section anymore, it would be better to remove it from the template. ❌ 🤓

2023-03-22 10:47 UTC, duskotmane commented on README.md
> +<!-- TABLE OF CONTENTS -->
okay I will remove them all

2023-03-22 10:47 UTC, OTMANE-ECHCHAFYKY commented on README.md
> +- [❓ FAQ (OPTIONAL)](#faq)
alright I'll remove it as well

2023-03-22 10:56 UTC, ABDULALI3468 approved these changes
Hi @OTMANE-ECHCHAFYKY , 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 10:04 UTC, OTMANE-ECHCHAFYKY commented
Adding my first linters

2023-03-23 10:04 UTC, merged